cookietemple_version: '1.4.1 # <<COOKIETEMPLE_NO_BUMP>>'
domain: cli
language: python
project_slug: spatial_atlas_ssl
project_slug_no_hyphen: spatial_atlas_ssl
template_version: '2.1.1 # <<COOKIETEMPLE_NO_BUMP>>'
template_handle: cli-python
github_username: richtertill
creator_github_username: richtertill
is_github_repo: false
is_repo_private: false
is_github_orga: false
full_name: Till Richter
email: till.richter@helmholtz-munich.de
project_name: spatial_atlas_ssl
project_short_description: "Self-supervised learning for mask inpainting on large\
  \ spa\ntial atlasses such as the BICCN 2.0 data."
version: 0.1.0
license: MIT
