rules: "rules/"
adata: "example_files/img_1199670929.h5ad"
k_hop:
  - 2
  #- 3
radius:
  - 20
  #- 30



pretrain_epochs: 50
pretrain_lr: 0.002
pretrain_batch_size: 64
pretrain_patience: 10

train_epochs: 50
train_lr: 0.002
train_batch_size: 64
train_patience: 10

masking_mode:
    - 0.1
    #- 0.3
    - 0.5
    #- 0.7
    - 0.9

pretrain_structure:
    - "GCN"

