rules: "rules/"
adata_folder: "example_files/"
adata_name: "img_1199670929.h5ad"

output_folder: "snake_output/"

k_hop:
  - 2
  #- 3
radius:
  - 20
  #- 30



pretrain_epochs: 50
pretrain_lr: 0.002
pretrain_batch_size: 64
pretrain_patience: 10

train_epochs: 10
train_lr: 0.002
train_batch_size: 64
train_patience: 10

masking_mode:
    - 0.1
    #- 0.3
    - 0.5
    #- 0.7
    - 0.9

pretrain_structure:
    - "GCN"

